export const ACTION_SEARCH_ITEMS_FETCH = 'SEARCH_ITEMS_FETCH';
export const ACTION_SEARCH_ITEMS_FETCH_SUCCESS = 'SEARCH_ITEMS_FETCH_SUCCESS';
export const ACTION_SEARCH_ITEMS_FETCH_ERROR = 'SEARCH_ITEMS_FETCH_ERROR';
export const ACTION_ACTIVATE_SEARCH = 'ACTIVATE_SEARCH';